apiVersion: v1
kind: Service
metadata:
  name: tracing-app
  namespace: tracing
spec:
  selector:
    app: tracing-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
